import bcrypt from 'bcrypt'
import dotenv from 'dotenv'
dotenv.config()

import { PrismaClient } from '../src/generated/prisma/client.js'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log('Seeding database...')

  // Nettoyer la BDD avant de re-seeder
  await prisma.applicationDocument.deleteMany()
  await prisma.application.deleteMany()
  await prisma.vehicle.deleteMany()
  await prisma.user.deleteMany()

  await prisma.vehicle.createMany({
    data: [
      {
        brand: 'Renault',
        model: 'Clio V',
        year: 2022,
        mileage: 15000,
        fuelType: 'petrol',
        transmission: 'manual',
        power: 90,
        doors: 5,
        seats: 5,
        color: 'Bleu',
        price: 16990,
        listingType: 'purchase',
        status: 'available',
        description: 'Citadine compacte, faible kilométrage, premier propriétaire.',
        images: [],
      },
      {
        brand: 'Peugeot',
        model: '3008',
        year: 2021,
        mileage: 32000,
        fuelType: 'diesel',
        transmission: 'automatic',
        power: 130,
        doors: 5,
        seats: 5,
        color: 'Gris',
        price: 389,
        minDeposit: 3000,
        listingType: 'rental',
        status: 'available',
        description: 'SUV familial, boîte automatique, entretien à jour.',
        images: [],
      },
      {
        brand: 'Citroën',
        model: 'C3',
        year: 2023,
        mileage: 8000,
        fuelType: 'petrol',
        transmission: 'manual',
        power: 83,
        doors: 5,
        seats: 5,
        color: 'Rouge',
        price: 17490,
        listingType: 'purchase',
        status: 'available',
        description: 'Citadine récente, très faible kilométrage, garantie constructeur.',
        images: [],
      },
      {
        brand: 'BMW',
        model: 'Série 3',
        year: 2020,
        mileage: 45000,
        fuelType: 'diesel',
        transmission: 'automatic',
        power: 190,
        doors: 4,
        seats: 5,
        color: 'Noir',
        price: 32900,
        listingType: 'purchase',
        status: 'available',
        description: 'Berline sportive, finition M Sport, intérieur cuir.',
        images: [],
      },
      {
        brand: 'Volkswagen',
        model: 'Golf VIII',
        year: 2022,
        mileage: 22000,
        fuelType: 'petrol',
        transmission: 'automatic',
        power: 150,
        doors: 5,
        seats: 5,
        color: 'Blanc',
        price: 299,
        minDeposit: 2500,
        listingType: 'rental',
        status: 'available',
        description: 'Compacte premium, faible consommation, équipement complet.',
        images: [],
      },
      {
        brand: 'Tesla',
        model: 'Model 3',
        year: 2023,
        mileage: 12000,
        fuelType: 'electric',
        transmission: 'automatic',
        power: 283,
        doors: 4,
        seats: 5,
        color: 'Blanc',
        price: 38900,
        listingType: 'purchase',
        status: 'available',
        description: 'Autonomie 491km, Autopilot inclus, recharge rapide.',
        images: [],
      },
      {
        brand: 'Toyota',
        model: 'Yaris',
        year: 2021,
        mileage: 28000,
        fuelType: 'hybrid',
        transmission: 'automatic',
        power: 116,
        doors: 5,
        seats: 5,
        color: 'Gris',
        price: 18900,
        listingType: 'purchase',
        status: 'available',
        description: 'Hybride économique, entretien Toyota, faible consommation.',
        images: [],
      },
      {
        brand: 'Audi',
        model: 'A4',
        year: 2020,
        mileage: 52000,
        fuelType: 'diesel',
        transmission: 'automatic',
        power: 163,
        doors: 4,
        seats: 5,
        color: 'Gris',
        price: 29500,
        listingType: 'purchase',
        status: 'available',
        description: 'Berline executive, full options, historique entretien complet.',
        images: [],
      },
      {
        brand: 'Mercedes',
        model: 'Classe A',
        year: 2022,
        mileage: 18000,
        fuelType: 'petrol',
        transmission: 'automatic',
        power: 136,
        doors: 5,
        seats: 5,
        color: 'Bleu',
        price: 349,
        minDeposit: 3000,
        listingType: 'rental',
        status: 'available',
        description: 'Compacte premium, intérieur haut de gamme, garantie incluse.',
        images: [],
      },
      {
        brand: 'Ford',
        model: 'Puma',
        year: 2023,
        mileage: 5000,
        fuelType: 'hybrid',
        transmission: 'manual',
        power: 125,
        doors: 5,
        seats: 5,
        color: 'Orange',
        price: 24900,
        listingType: 'purchase',
        status: 'available',
        description: 'SUV compact hybride, très faible kilométrage.',
        images: [],
      },
      {
        brand: 'Dacia',
        model: 'Sandero',
        year: 2022,
        mileage: 19000,
        fuelType: 'petrol',
        transmission: 'manual',
        power: 90,
        doors: 5,
        seats: 5,
        color: 'Blanc',
        price: 13500,
        listingType: 'purchase',
        status: 'available',
        description: 'Citadine économique, idéale premier véhicule.',
        images: [],
      },
      {
        brand: 'Nissan',
        model: 'Qashqai',
        year: 2021,
        mileage: 38000,
        fuelType: 'diesel',
        transmission: 'manual',
        power: 115,
        doors: 5,
        seats: 5,
        color: 'Noir',
        price: 319,
        minDeposit: 2000,
        listingType: 'rental',
        status: 'available',
        description: 'SUV familial spacieux, faible consommation.',
        images: [],
      },
      {
        brand: 'Hyundai',
        model: 'Tucson',
        year: 2023,
        mileage: 14000,
        fuelType: 'hybrid',
        transmission: 'automatic',
        power: 230,
        doors: 5,
        seats: 5,
        color: 'Gris',
        price: 36900,
        listingType: 'purchase',
        status: 'available',
        description: 'SUV hybride rechargeable, équipement complet, garantie 5 ans.',
        images: [],
      },
      {
        brand: 'Fiat',
        model: '500',
        year: 2022,
        mileage: 9000,
        fuelType: 'electric',
        transmission: 'automatic',
        power: 118,
        doors: 3,
        seats: 4,
        color: 'Vert',
        price: 22900,
        listingType: 'purchase',
        status: 'available',
        description: 'Citadine électrique, parfaite pour la ville, recharge rapide.',
        images: [],
      },
      {
        brand: 'Mini',
        model: 'Cooper',
        year: 2021,
        mileage: 25000,
        fuelType: 'petrol',
        transmission: 'manual',
        power: 136,
        doors: 3,
        seats: 4,
        color: 'Rouge',
        price: 21900,
        listingType: 'purchase',
        status: 'available',
        description: 'Citadine premium, look sportif, intérieur soigné.',
        images: [],
      },
      {
        brand: 'Skoda',
        model: 'Octavia',
        year: 2022,
        mileage: 21000,
        fuelType: 'diesel',
        transmission: 'automatic',
        power: 150,
        doors: 5,
        seats: 5,
        color: 'Bleu',
        price: 26900,
        listingType: 'purchase',
        status: 'available',
        description: 'Break familial, grand coffre, très bon rapport qualité-prix.',
        images: [],
      },
      {
        brand: 'Volvo',
        model: 'XC40',
        year: 2023,
        mileage: 11000,
        fuelType: 'electric',
        transmission: 'automatic',
        power: 231,
        doors: 5,
        seats: 5,
        color: 'Noir',
        price: 549,
        minDeposit: 4000,
        listingType: 'rental',
        status: 'available',
        description: 'SUV électrique premium, autonomie 425km, sécurité maximale.',
        images: [],
      },
      {
        brand: 'Seat',
        model: 'Leon',
        year: 2021,
        mileage: 34000,
        fuelType: 'petrol',
        transmission: 'manual',
        power: 115,
        doors: 5,
        seats: 5,
        color: 'Blanc',
        price: 19500,
        listingType: 'purchase',
        status: 'available',
        description: 'Compacte dynamique, faible consommation, bon état général.',
        images: [],
      },
      {
        brand: 'Opel',
        model: 'Corsa',
        year: 2022,
        mileage: 16000,
        fuelType: 'electric',
        transmission: 'automatic',
        power: 136,
        doors: 5,
        seats: 5,
        color: 'Gris',
        price: 249,
        minDeposit: 1500,
        listingType: 'rental',
        status: 'available',
        description: "Citadine électrique, idéale trajets urbains, faible coût d'usage.",
        images: [],
      },
      {
        brand: 'Kia',
        model: 'Sportage',
        year: 2023,
        mileage: 7000,
        fuelType: 'hybrid',
        transmission: 'automatic',
        power: 230,
        doors: 5,
        seats: 5,
        color: 'Rouge',
        price: 34900,
        listingType: 'purchase',
        status: 'available',
        description: 'SUV hybride récent, garantie 7 ans, équipement haut de gamme.',
        images: [],
      },
    ],
  })

  const adminPassword = await bcrypt.hash('admin123', 10)
  const userPassword = await bcrypt.hash('user1234', 10)

  await prisma.user.upsert({
    where: { email: 'admin@m-motors.com' },
    update: {},
    create: {
      firstName: 'Admin',
      lastName: 'M-Motors',
      email: 'admin@m-motors.com',
      passwordHash: adminPassword,
      role: 'admin',
    },
  })

  await prisma.user.upsert({
    where: { email: 'user@test.com' },
    update: {},
    create: {
      firstName: 'Ryme',
      lastName: 'Lehna',
      email: 'user@test.com',
      passwordHash: userPassword,
      role: 'client',
    },
  })

  console.log('Admin: admin@m-motors.com / admin123')
  console.log('Client: user@test.com / user1234')
  console.log('Seed completed.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })